apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

images:
  - name: docker.io/yourname/spring-boot-server
    newTag: prod
  - name: docker.io/yourname/react-client
    newTag: prod

patchesStrategicMerge:
  - replicas-patch.yaml
