apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-server
  labels:
    app: spring-boot-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-server
  template:
    metadata:
      labels:
        app: spring-boot-server
    spec:
      containers:
        - name: spring-boot-server
          image: docker.io/ahmedikram567/spring-boot-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/testdb?useSSL=false&allowPublicKeyRetrieval=true
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: MYSQL_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: MYSQL_PASSWORD
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
